### ISSUE TITLE
Models available elsewhere?

### ISSUE THREAD

**Issue by RKelln** [bcmi/BargainNet-Image-Harmonization#1]
Hi, I'd like to give this a try but I'm having trouble downloading the models. Is there another location that you could upload them? Thanks very much!

**Comment by Mia-Cong** [comment]
Hi, I added an alternative address (https://bcmi.cloud:5001/sharing/yZlCycSZo) in the Readme just now and hope that could work for you.

**Comment by Mia-Cong** [comment]
> Hi, I'd like to give this a try but I'm having trouble downloading the models. Is there another location that you could upload them? Thanks very much!

Hi, I added an alternative address (https://bcmi.cloud:5001/sharing/yZlCycSZo) in the Readme just now and hope that could work for you.

**Comment by RKelln** [comment]
The link in the readme worked (but not the one in the comment), thanks very much!

**Comment by jeya-maria-jose** [comment]
Hi, Thank you for sharing the code and models. However, I am unable to download the models from both the links. Is it possible to give another alternative ? It would be really great ! Thank you !

**Comment by Mia-Cong** [comment]
> Hi, Thank you for sharing the code and models. However, I am unable to download the models from both the links. Is it possible to give another alternative ? It would be really great ! Thank you !

I have also uploaded the model to Google Drive (https://drive.google.com/file/d/1CzfTf6A7ra8TDT1IUnZvXAvljks4xjbG/view?usp=sharing). It could work for you~

**Comment by jeya-maria-jose** [comment]
Thank you so much !
