### ISSUE TITLE
Apply to the animated image domain

### ISSUE THREAD

**Issue by Echo411** [bcmi/BargainNet-Image-Harmonization#10]
hi, this is a great job! I want to apply the pre-trained model to the animation image domain, but I find that the performance is not as good as that of the real image domain.  **I hope to get your suggestions on how to improve the performance of the model in animation image domains:**
1. Can the model performance be improved by modifying the parameters? What parameters should be changed?
2. If I need to train the model, should I fine-tune the model or retrain the model? What should I do if I want to fine-tune the model?
3. Could you share some information on what setup you used for the training of the model?  how many Gpus/for how long?
4. The output image size has been changed to 256*256, how to keep the output image size of the original image?

![d60-131_1_3](https://github.com/bcmi/BargainNet-Image-Harmonization/assets/60573292/5045410b-9519-49f1-a09e-5532ee606eec)
（a）composite image
![d60-131_1_3](https://github.com/bcmi/BargainNet-Image-Harmonization/assets/60573292/f8a15ceb-3b39-4273-8d50-638b16850206)
（b）Code generated image

Looking forward to your reply!

**Comment by ustcnewly** [comment]
When the background is cartoon image, you can try painterly image harmonization:
https://github.com/bcmi/PHDNet-Painterly-Image-Harmonization
https://github.com/bcmi/PHDiffusion-Painterly-Image-Harmonization
