### ISSUE TITLE
module 'albumentations.augmentations.transforms' has no attribute 'Resize'

### ISSUE THREAD

**Issue by WayneChen-cloud** [bcmi/BargainNet-Image-Harmonization#2]
When I try to run this repo, the error is reported.
"AttributeError: module 'albumentations.augmentations.transforms' has no attribute 'Resize'"
details:
File "/BargainNet-Image-Harmonization/data/base_dataset.py", line 68, in get_transform
transform_list.append(transforms.Resize(256,256))

**Comment by WayneChen-cloud** [comment]
how can I deal with it?

**Comment by WayneChen-cloud** [comment]
I figure it out.
I suggest that the line 67 in base_dataset.py "transform_list.append(transforms.Resize(256, 256))" should be changed to "transform_list.append(Resize(256, 256))".
Thank you for sharing the code and models!

**Comment by wmpauli** [comment]
just want to add that in addition to the change proposed above, `Resize` also needs to be imported, e.g. in line 6, like so

`from albumentations import HorizontalFlip, RandomResizedCrop, Compose, DualTransform, Resize`
