### ISSUE TITLE
多卡训练的问题

### ISSUE THREAD

**Issue by ymj98** [bcmi/BargainNet-Image-Harmonization#4]
您好，请问一下代码是只支持单卡训练么？可以进行多卡训练么

**Comment by cjy-4** [comment]
We set the batch size to 1 in our experiments and training on single GPU.
Basically, we have implemented some code here to support multiple GPUs:
https://github.com/bcmi/BargainNet-Image-Harmonization/blob/faddca22f7e12a35ba6141031fe687aec95fe881/models/networks.py#L112-L116
You can set --gpu_ids 0,1,... to work on multiple GPUs.
