### ISSUE TITLE
about test.py  error    

### ISSUE THREAD

**Issue by zhanghongyong123456** [bcmi/BargainNet-Image-Harmonization#5]
when  i download trained model ，put it under  ./checkpoints/<experiment_name>/.  <experiment_name>  What is this? it is  latest_net_E.pth or latest_net_G.pth？
when run test.py :   python test.py --name latest_net_G.pth --model bargainnet --dataset_mode iharmony4 --is_train 0 --norm batch --preprocess resize --gpu_ids 0 --input_nc 20 --netG s2ad

i have a error,FileNotFoundError: [Errno 2] No such file or directory: './checkpoints\\latest_net_G.pth\\test_opt.txt',what is   test_opt.txt.i 
 don,t have  this  file.

![image](https://user-images.githubusercontent.com/48466610/142366977-5c008a25-a238-4885-9617-25b235013e9b.png)
![image](https://user-images.githubusercontent.com/48466610/142367066-606ee54f-3f9b-4f4d-ac2e-e9164f0d4b48.png)

**Comment by Mia-Cong** [comment]
<experiment_name> is the name of the experiment, a directory inside checkpoints/ containing both latest_net_E.pth and latest_net_G.pth. For example, put latest_net_E.pth and latest_net_G.pth in ./checkpoints/pretrained/, the test command could be: python test.py --name pretrained --model bargainnet --dataset_mode iharmony4 --is_train 0 --norm batch --preprocess resize --gpu_ids 0 --input_nc 20 --netG s2ad

**Comment by Mia-Cong** [comment]
<experiment_name> is the name of the experiment, a directory inside checkpoints/ containing both latest_net_E.pth and latest_net_G.pth. For example, put latest_net_E.pth and latest_net_G.pth in ./checkpoints/pretrained/, the test command could be: python test.py --name pretrained --model bargainnet --dataset_mode iharmony4 --is_train 0 --norm batch --preprocess resize --gpu_ids 0 --input_nc 20 --netG s2ad
