### ISSUE TITLE
about test issues

### ISSUE THREAD

**Issue by zhanghongyong123456** [bcmi/BargainNet-Image-Harmonization#6]
1.  when runing  python test.py --name <experiment_name> --model bargainnet --dataset_mode iharmony4 --is_train 0 --norm batch --preprocess resize --gpu_ids 0 --input_nc 20 --netG s2ad   
![image](https://user-images.githubusercontent.com/48466610/143395234-57b3b4a3-a303-40ae-90f1-40eda227d199.png)
What computer configuration is required to run this project
2. How to deal with my own image, if I have a directly synthesized image, how to harmonize？
What data is needed to achieve it
python test.py --name <experiment_name> --model bargainnet --dataset_mode iharmony4 --is_train 0 --norm batch --preprocess resize --gpu_ids 0 --input_nc 20 --netG s2ad    
![image](https://user-images.githubusercontent.com/48466610/143396358-8becd7dc-a757-4e39-999b-c4ddad6b958e.png)
This is the result of my running, it’s not right, I don’t know where the problem is
3. Is it possible to process 4k video streams in real time，That is, what is the processed fps and the maximum resolution of the processed image

**Comment by zhanghongyong123456** [comment]
> 

I tested an image separately and got this result, I don’t know why，
![c1815_500925_1](https://user-images.githubusercontent.com/48466610/143520059-59d0dada-56ef-485f-a138-89c0b3175865.jpg)
HCOCO  c1815_500925_1.jpg pic

**Comment by zhanghongyong123456** [comment]
> > 
> 
> I tested an image separately and got this result, I don’t know why， ![c1815_500925_1](https://user-images.githubusercontent.com/48466610/143520059-59d0dada-56ef-485f-a138-89c0b3175865.jpg) HCOCO c1815_500925_1.jpg pic

![image](https://user-images.githubusercontent.com/48466610/143520191-5d893ff3-1080-4345-9808-d00a04ee60ec.png)
this is test log

**Comment by cjy-4** [comment]
1. We train our network on ubuntu 16.04 LTS operation system, with 64GB memory, Intel Core i7-8700K CPU, and two
GeForce GTX 1080 Ti GPUs.
2. You need to provide the same data structure as iHarmony4 dataset, and modify the dir to your own data:
https://github.com/bcmi/BargainNet-Image-Harmonization/blob/faddca22f7e12a35ba6141031fe687aec95fe881/data/iharmony4_dataset.py#L31
