### ISSUE TITLE
About  iharmony4 data structure and  inharmony level

### ISSUE THREAD

**Issue by yangshunDragon** [bcmi/BargainNet-Image-Harmonization#7]
Hello, thanks for opening source the great project.

I have 2 issuss when reproduce the project:
1. What is the exact data structure of iharmony4? Do you train the 4 subclass once? When I run the training, I have bugs for data loading. And I have not change the original iharmony4 data structure.
2. Whear is the code to predict the inharmony level of a composite image by calculating the Euclidean distance between two domain?

thanks in advance!

**Comment by cjy-4** [comment]
1. We train on the whole iHarmony4 dataset.
Remember to change this to your own dataset root:
https://github.com/bcmi/BargainNet-Image-Harmonization/blob/faddca22f7e12a35ba6141031fe687aec95fe881/options/base_options.py#L23

2. You can calculate the Euclidean distance between
https://github.com/bcmi/BargainNet-Image-Harmonization/blob/faddca22f7e12a35ba6141031fe687aec95fe881/models/bargainnet_model.py#L273 and
https://github.com/bcmi/BargainNet-Image-Harmonization/blob/faddca22f7e12a35ba6141031fe687aec95fe881/models/bargainnet_model.py#L274
