### ISSUE TITLE
Evaluation using real image

### ISSUE THREAD

**Issue by shravan-d** [bcmi/BargainNet-Image-Harmonization#8]
While evaluating the model, it seems like the real (target) image has to be passed as input for the discriminator to create a bg_style_map, which is then passed through the generator concatenated with the composite. What should be done when we do not have the real image? Isn't the aim to find the real image?

**Comment by taoxinhao13** [comment]
The background of the real image and the composite image are exactly the same, so it can be replaced with the composite image.
